/** ~230 of the most common English words. Used for the default `english` mode. */
export const ENGLISH: string[] = [
  'the', 'be', 'to', 'of', 'and', 'a', 'in', 'that', 'have', 'it', 'for', 'not',
  'on', 'with', 'he', 'as', 'you', 'do', 'at', 'this', 'but', 'his', 'by', 'from',
  'they', 'we', 'say', 'her', 'she', 'or', 'an', 'will', 'my', 'one', 'all',
  'would', 'there', 'their', 'what', 'so', 'up', 'out', 'if', 'about', 'who',
  'get', 'which', 'go', 'me', 'when', 'make', 'can', 'like', 'time', 'no', 'just',
  'him', 'know', 'take', 'people', 'into', 'year', 'your', 'good', 'some', 'could',
  'them', 'see', 'other', 'than', 'then', 'now', 'look', 'only', 'come', 'its',
  'over', 'think', 'also', 'back', 'after', 'use', 'two', 'how', 'our', 'work',
  'first', 'well', 'way', 'even', 'new', 'want', 'because', 'any', 'these', 'give',
  'day', 'most', 'us', 'world', 'find', 'where', 'much', 'before', 'great', 'such',
  'water', 'still', 'place', 'high', 'small', 'large', 'next', 'early', 'young',
  'important', 'few', 'public', 'bad', 'same', 'able', 'house', 'point', 'every',
  'right', 'study', 'book', 'eye', 'job', 'word', 'business', 'issue', 'side',
  'kind', 'head', 'far', 'black', 'long', 'both', 'little', 'house', 'last',
  'night', 'live', 'power', 'order', 'open', 'fact', 'though', 'feel', 'three',
  'state', 'never', 'become', 'between', 'high', 'really', 'something', 'family',
  'leave', 'turn', 'start', 'hand', 'show', 'part', 'against', 'play', 'move',
  'while', 'love', 'mean', 'keep', 'student', 'begin', 'old', 'help', 'talk',
  'where', 'home', 'offer', 'water', 'room', 'mother', 'area', 'money', 'story',
  'fact', 'month', 'lot', 'study', 'book', 'word', 'change', 'light', 'lead',
  'system', 'set', 'order', 'real', 'team', 'level', 'best', 'true', 'school',
  'human', 'history', 'idea', 'walk', 'white', 'reason', 'face', 'almost', 'love',
  'often', 'social', 'sense', 'simple', 'cause', 'plant', 'space', 'voice',
  'music', 'color', 'green', 'river', 'quiet', 'happy', 'energy', 'strong',
];
