/** Additional, less-frequent words layered on top of ENGLISH for `english-1k`. */
export const EXTENDED: string[] = [
  'absolute', 'acoustic', 'adventure', 'although', 'analyze', 'ancient',
  'apparent', 'approach', 'argument', 'attention', 'available', 'balance',
  'beautiful', 'behavior', 'benefit', 'beyond', 'boundary', 'breeze', 'brilliant',
  'calendar', 'campaign', 'capacity', 'category', 'ceremony', 'challenge',
  'chemical', 'circuit', 'collapse', 'comfort', 'community', 'complex', 'concept',
  'conflict', 'consider', 'constant', 'continue', 'contrast', 'creative',
  'culture', 'curious', 'decision', 'delicate', 'describe', 'develop', 'diamond',
  'discover', 'distance', 'dramatic', 'economy', 'elegant', 'element', 'emerge',
  'emotion', 'engineer', 'enormous', 'entire', 'envelope', 'establish', 'evidence',
  'exchange', 'exercise', 'explain', 'exposure', 'extreme', 'fabric', 'feature',
  'festival', 'fortune', 'fragment', 'function', 'gallery', 'generate', 'genuine',
  'gradual', 'gravity', 'harmony', 'horizon', 'identity', 'imagine', 'immense',
  'industry', 'instance', 'interest', 'internal', 'journey', 'junior', 'kingdom',
  'language', 'lecture', 'liberty', 'magnetic', 'majority', 'maximum', 'measure',
  'mechanic', 'medical', 'memory', 'mineral', 'mixture', 'moment', 'mountain',
  'mystery', 'narrow', 'natural', 'network', 'neutral', 'notable', 'observe',
  'obvious', 'organic', 'original', 'outcome', 'overcome', 'parallel', 'passion',
  'pattern', 'perfect', 'physical', 'pioneer', 'pleasure', 'positive', 'possible',
  'practice', 'precise', 'predict', 'premium', 'prepare', 'pressure', 'primary',
  'private', 'process', 'produce', 'project', 'promise', 'protect', 'provide',
  'purpose', 'quality', 'quantum', 'rapidly', 'reality', 'receive', 'recover',
  'reflect', 'regular', 'release', 'remote', 'require', 'resolve', 'respect',
  'response', 'reverse', 'satellite', 'science', 'section', 'segment', 'sensitive',
  'separate', 'sequence', 'serious', 'service', 'session', 'shadow', 'silence',
  'similar', 'society', 'solution', 'special', 'species', 'spectrum', 'stable',
  'standard', 'strategy', 'stream', 'structure', 'subject', 'success', 'suggest',
  'summary', 'support', 'surface', 'surprise', 'survive', 'symbol', 'talent',
  'tangent', 'tension', 'texture', 'theory', 'thunder', 'tornado', 'tradition',
  'transfer', 'triangle', 'typical', 'ultimate', 'uniform', 'universe', 'unusual',
  'vacuum', 'valley', 'variety', 'vehicle', 'venture', 'version', 'vertical',
  'veteran', 'victory', 'village', 'vintage', 'virtual', 'vision', 'volume',
  'voltage', 'wander', 'warmth', 'weather', 'welcome', 'whisper', 'wisdom',
  'wonder', 'workshop', 'yearly', 'zenith',
];
